#!/bin/bash

INPUT_FILE_PATH=$1
OUTPUT_FILEPATH=$2
WORD_LENGTH=$3

INPUT_TEXT_PROCESSING=$(<$INPUT_FILE_PATH)
INPUT_TEXT_TO_SPLIT=$INPUT_TEXT_PROCESSING
INPUT_TEXT_PROCESSING_ARRAY=$(echo $INPUT_TEXT_TO_SPLIT | perl -pe "s/\xC2\xA0/\x20/g")

for WORD in $INPUT_TEXT_PROCESSING_ARRAY; do

	if [ ${#WORD} -le "$WORD_LENGTH" ]; then

		INPUT_TEXT_PROCESSING=$(echo "$INPUT_TEXT_PROCESSING" | perl -pe "s/$WORD\x20/$WORD\xC2\xA0/g")		
	fi
   
done

echo "$INPUT_TEXT_PROCESSING" > $OUTPUT_FILEPATH